name: CI - All Implementations

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  python:
    uses: ./.github/workflows/python.yml
    
  rust:
    uses: ./.github/workflows/rust.yml
    
  cpp:
    uses: ./.github/workflows/cpp.yml
    
  go:
    uses: ./.github/workflows/go.yml

  status-check:
    runs-on: ubuntu-latest
    needs: [python, rust, cpp, go]
    if: always()
    steps:
    - name: Check all implementations passed
      run: |
        if [[ "${{ needs.python.result }}" == "success" && \
              "${{ needs.rust.result }}" == "success" && \
              "${{ needs.cpp.result }}" == "success" && \
              "${{ needs.go.result }}" == "success" ]]; then
          echo "✅ All implementations passed!"
          exit 0
        else
          echo "❌ Some implementations failed:"
          echo "Python: ${{ needs.python.result }}"
          echo "Rust: ${{ needs.rust.result }}"
          echo "C++: ${{ needs.cpp.result }}"
          echo "Go: ${{ needs.go.result }}"
          exit 1
        fi