name: Python Build and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'bjst/**'
      - 'tests/**'
      - '.pylintrc'
      - '.github/workflows/python.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'bjst/**'
      - 'tests/**'
      - '.pylintrc'
      - '.github/workflows/python.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check code formatting
      run: |
        autopep8 --diff --recursive bjst/
        if [ $? -ne 0 ]; then
          echo "Code formatting issues found. Run 'autopep8 --in-place --recursive bjst/' to fix."
          exit 1
        fi

    - name: Run pylint
      run: |
        pylint bjst/

    - name: Run unit tests with pytest
      run: |
        python -m pytest tests/ -v

    - name: Run unit tests with unittest (fallback)
      if: failure()
      run: |
        python -m unittest discover tests/ -v

    - name: Test package execution
      run: |
        python -m bjst --help